all: job1  job2  job3  job4  job5  job6  job7  job8  job9  job10 job11 job12 job13 job14 job15 job16 job17 job18 job19 job20 job21 job22 job23 job24 job25 job26 job27 job28 job29 job30 job31 job32 
job1  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 1 9   21  206  178  129  220   11
job2  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 2 74   99   69  115  155   93   83
job3  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 3 198  116  133  175  105   60  226
job4  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 4 63  141  125  136  191  217  158
job5  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 5 54  150   30   17  111  230  210
job6  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 6 215   34  160  148  224   87   72
job7  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 7 182  117  112  181  170  223   95
job8  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 8 10  201  174  168  156  122   37
job9  :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 9 97  166  149  219  100   70   62
job10 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 10 200   27   46  135   20   39  192
job11 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 11 171   42   16  167  118  152  169
job12 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 12 7   43   22   91  134   47   80
job13 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 13 102  176  199  144  197  216    6
job14 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 14 188  139  231    5    4  196  153
job15 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 15 163  177  186  119  123   59   53
job16 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 16 2  151  101  172  162   51   89
job17 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 17 193  212  114  164   71   35   15
job18 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 18 94  205  103   49   64  195   32
job19 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 19 75  161   48  128  207  121  124
job20 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 20 73   86  157  131  154  104  145
job21 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 21 28  159   18  113   40   33   81
job22 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 22 147   13   44   38  179   61  110
job23 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 23 66   98   12   41   55   76  132
job24 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 24 228   58  211  183  214   50  194
job25 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 25 173  180   29   90   19   79   78
job26 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 26 23  107  221  203  143   52  184
job27 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 27 108   24   82  189   57  130  109
job28 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 28 3  208   65  190  126  137   45
job29 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 29 138   26  229  202    1   96  142
job30 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 30 88  222  106    8  187   31  120
job31 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 31 85   25   36  225  213  227  165
job32 :
	nice -n19 /home/skraft/neuroinf/UE2.4/runmatlab /home/skraft/neuroinf/UE2.4/UEMainAnalyseWindow /home/skraft/local.scratch/ 32 84  204  146  127  140   92   68   77  218  209   56   14  185   67
