function splashscreen(mode)

switch mode
 case 'create'

 sp=get(0,'ScreenSize');
 f=figure(...
    'Tag','SplashScreen',...
    'MenuBar','none',...
    'Resize', 'off', ...
    'Name', 'SplashScreen', ...
    'NumberTitle', 'off', ...
    'Position',[20, floor(sp(4)/2)-175,500,350], ...
    'Color', [0.87 0.87 0.89]...
   );
 a=axes(...
     'Clipping', 'off',...
     'Visible','off',...
     'Units','pixels',...
     'Position',[5 160 150 150],...
     'XLim',[1 100],...
     'YLim',[1 100]...
   );

l=line(...
 'LineStyle','none',...
 'Marker','o',...
 'MarkerFaceColor',[0 0 0],...
 'MarkerEdgeColor',[0 0 0],...
 'MarkerSize',6,...
 'XData',[40 40 60 60  30 50 55 71 49 30],...
 'YData',[20 40 40 60  25 15 31 43 65 55],...
 'Color',[1 0 0]...
);
l=line(...
 'LineStyle','none',...
 'Marker','square',...
 'MarkerFaceColor','none',...
 'MarkerEdgeColor',[1 0 0],...
 'MarkerSize',20,...
 'XData',[40 40 60 60],...
 'YData',[20 40 40 60],...
 'Color',[1 0 0]...
);


 t=uicontrol(...
    'Style','Text',...
    'Position',[100 280 300 40],...
    'BackgroundColor',get(f,'Color'),...
    'FontName','Helvetica',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment', 'left', ...
    'String','Unitary Events Analysis'...
   );

 t=uicontrol(...
    'Style','Text',...
    'Position',[140 235 350 40],...
    'BackgroundColor',get(f,'Color'),...
    'FontName','Helvetica',...
    'FontAngle','italic',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment', 'left', ...
    'String','Version 2.3 '...
   );

 t=uicontrol(...
    'Style','Text',...
    'Position',[200 175 250 55],...
    'BackgroundColor',get(f,'Color'),...
    'FontName','Helvetica',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment', 'center', ...
    'String',{'Sonja Gruen','RIKEN BSI','Wako-City, Japan'}...
   );

 t=uicontrol(...
    'Style','Text',...
    'Position',[140 90 350 55],...
    'BackgroundColor',get(f,'Color'),...
    'FontName','Helvetica',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment', 'center', ...
    'String',{'Markus Diesmann','RIKEN BSI',...
              'Wako-City, Japan'}...
   );

 t=uicontrol(...
    'Style','Pushbutton',...
    'BackgroundColor',get(f,'Color'),...
    'Position',[350 10 70 30],...
    'FontName','Helvetica',...
    'FontSize',14,...    
    'String','Continue',...
    'Callback','splashscreen(''close'')'...
   );

t=uicontrol(...
    'Style','Pushbutton',...
    'BackgroundColor',get(f,'Color'),...
    'Position',[30 10 70 30],...
    'FontName','Helvetica',...
    'FontSize',14,...    
    'String','Version',...
    'Callback','versionscreen(''create'')'...
   );

t=uicontrol(...
    'Style','Pushbutton',...
    'BackgroundColor',get(f,'Color'),...
    'Position',[120 10 70 30],...
    'FontName','Helvetica',...
    'FontSize',14,...    
    'String','License',...
    'Callback','licensescreen(''create'')'...
   );

 t=text(...
    'Position',[40 -60],...
    'FontName','Helvetica',...
    'FontSize',14,...   
    'FontWeight','bold',... 
    'Color',[0 0 1],...   
    'String','Locate Us!',...
    'ButtonDownFcn',...
      'websites(''home'')'...
   ); 

 t=text(...
    'Position',[142 5],...
    'FontName','Helvetica',...
    'FontSize',12,...   
    'FontWeight','bold',... 
    'Color',[0 0 1],...   
    'String','gruen@brain.riken.jp',...
    'ButtonDownFcn',...
      'websites(''mailgruen'')'...
   ); 

 t=text(...
    'Position',[142 -50],...
    'FontName','Helvetica',...
    'FontSize',12,...   
    'FontWeight','bold',... 
    'Color',[0 0 1],...   
    'String','diesmann@brain.riken.jp',...
    'ButtonDownFcn',...
      'websites(''maildiesmann'')'...
   ); 


 case 'close' 
  f=findobj('Tag','VersionScreen');
  close(f);
  f=findobj('Tag','License');
  close(f);
  f=findobj('Tag','SplashScreen');
  close(f); 

 otherwise
  error('License::UnknownMode');
end
