function constructST()
% GUI for creating an own spike train 
%
% 
%
% H. Walz Feb 2008
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de


global nsFile;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;


try

    % Check if the sortSpikes GUI is already open
    if ishandle(findobj('tag', 'constructST'))
        close(findobj('tag', 'constructST'));
    end;

    % GUI window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=100;
    GUIheight=15;

    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','constructST', ...
        'Name','construct own RF GUI',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'resize','off');

    % panels
    centralPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth/2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','constructST_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
    lowRightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth/2 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth/2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)/4],...
        'Tag','constructST_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
     upperRightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth/2 MESSAGEBAR_PANEL_HEIGHT+(GUIheight-MESSAGEBAR_PANEL_HEIGHT)/4,...
        GUIwidth/2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)*3/4],...
        'Tag','constructST_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','constructST_messageBarPanel');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','constructST_messageBarText',...
        'Enable','on',...
        'String','choose parameters for receptive field',...
        'HorizontalAlignment','left',...
        'Style','text');
    %%%%% text %%%%
 
       uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[14  11    20    1.2],...
        'Style','text',...
        'String','linear filter',...
        'Tag','constructST_gaborInfoLabelText',...
        'Enable','on');
    
       uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[0.5   5.7    48    1.2],...
        'Style','text',...
        'String','edit parameters for own receptive field',...
        'Tag','constructST_gaborInfoLabelText',...
        'Enable','on');
      uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[0.5    4.5    48    1.2],...
        'Style','text',...
        'String','gauss x and y, freq, phase and ori of cos, ellipsicity',...
        'Tag','constructST_parametersInfoLabelText',...
        'Enable','on');
   
    %%%%parameters to edit
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[14  7.5    20   1.2],...
        'Style','edit',...
        'String','matrix A',...
        'Tag','constructST_matrix',...
        'Enable','on');
     
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[3  3    5   1.2],...
        'Style','edit',...
        'String','[5]',...
        'Tag','constructST_sigmaX',...
        'Enable','on');
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[10  3    5    1.2],...
        'Style','edit',...
        'String','[5]',...
        'Tag','constructST_sigmaY',...
        'Enable','on');
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[17   3    5    1.2],...
        'Style','edit',...
        'String','[3]',...
        'Tag','constructST_f',...
        'Enable','on');
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[24   3    5    1.2],...
        'Style','edit',...
        'String','[3]',...
        'Tag','constructST_pha',...
        'Enable','on');
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[31   3    5    1.2],...
        'Style','edit',...
        'String','[3]',...
        'Tag','constructST_theta',...
        'Enable','on');
    %%%%ellipsicity is one if round   
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[38   3    5    1.2],...
        'Style','edit',...
        'String','[2]',...
        'Tag','constructST_gamma',...
        'Enable','on');
    
    
    
    
    %%%% Buttons %%%%
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[14 1.5 20 (BUTTON_HEIGHT)],...
        'Style','pushbutton',...
        'String','construct Gabor',...
        'Tag','constructST_GaborPushbutton',...
        'Enable','on',...
        'Callback',@constructGaborPushbuttonCallback);

    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[10 0 30 (BUTTON_HEIGHT)],...
        'Style','pushbutton',...
        'String','convolve with stimulus',...
        'Tag','constructST_convolvePushbutton',...
        'Enable','on',...
        'Callback',@convolvePushbuttonCallback);
    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[14  8.7    20   1.2],...
        'Style','pushbutton',...
        'String','load linear filter',...
        'Tag','constructST_loadPushbutton',...
        'Enable','on',...
        'Callback',@loadFilterPushbuttonCallback);
     uicontrol('Parent',lowRightPanel,...
        'Units','characters',...
        'Position',[5  1    30  1.5],...
        'Style','pushbutton',...
        'String','create poisson spiking',...
        'Tag','constructST_poissonPushbutton',...
        'Enable','on',...
        'Callback',@poissonPushbuttonCallback);
   

     %%%% Radio button group for the type of nonlinearity

    radioGroup = uibuttongroup('visible','on'...
        ,'Units','normalized',...
        'Position',[0.1 0.05 0.8 0.9],...
        'Parent',upperRightPanel,...
        'Tag','constructST_radioGroup',...
        'Title','nonlinearity');

    radioButton1 = uicontrol('Style','Radio',...
        'String','1) sigmoidal',...
        'Units','normalized',...
        'pos',[.25 .75 .5 .2],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','constructST_sigmoidal');
    radioButton2 = uicontrol('Style','Radio',...
        'String','2) squared',...
        'Units','normalized',...
        'pos',[.25 .5 .5 .2],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','constructST_squared');
    radioButton3 = uicontrol('Style','Radio',...
        'String','3) load arbitrary',...
        'Units','normalized',...
        'pos',[.25 .25 .5 .2],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','constructST_loadNonlin');
      uicontrol('Parent',radioGroup,...
        'Units','normalized',...
        'Position',[0.1  0    0.8    0.2],...
        'Style','edit',...
        'String','matrix B',...
        'Tag','constructST_matrixBText',...
        'Enable','on');
    



catch
    % if error occurs here, the window is closed, the error is rethrown
    % and then catched by the main window
    close(findobj('tag', 'constructST'));
    rethrow(lasterror);
end

function constructGaborPushbuttonCallback(a,b)
global linearFilter
freq=str2num(get(findobj('Tag','constructST_f'),'String'));
sx=str2num(get(findobj('Tag','constructST_sigmaX'),'String'));
sy=str2num(get(findobj('Tag','constructST_sigmaY'), 'String'));
gamma_x=str2num(get(findobj('Tag','constructST_gamma'),'String'));
theta=str2num(get(findobj('Tag','constructST_theta'),'String'));
pha=str2num(get(findobj('Tag','constructST_pha'),'String'));
linearFilter=constructGabor('f',0.1,'theta',2*pi,'sdy',8,'sdx',1,'pha',0,'gamma_x',0.01);
linearFilter=reshape(linearFilter,[1,prod(size(linearFilter))]);


function loadFilterPushbuttonCallback(a,b)
global linearFilter
fileName=get(findobj('Tag','constructST_matrix'),'String');
linearFilter=evalin('base',fileName);


function convolvePushbuttonCallback(a,b)
global linearFilter linearizedStimulus
convolvedFilter=convolveStim('stim',linearizedStimulus,'linearFilter',linearFilter);

