function makeStrfCohGUI()

% GUI for analyzing some characteristics of the coherence between response
% and linear prediction
%
%
%
% H. Walz Oct. 2008
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de
global nsFile;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;


try

    % Check if the sortSpikes GUI is already open
    if ishandle(findobj('tag', 'makeStrfCohGUI'))
        close(findobj('tag', 'makeStrfCohGUI'));
    end;

    % GUI window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=30;
    GUIheight=17;

    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','makeStrfCohGUI', ...
        'Name','makeStrfCohGUI',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'resize','off');

    % panels
    centralPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','makeStrfCohGUI_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','makeStrfCohGUI_messageBarPanel');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','makeStrfCohGUI_messageBarText',...
        'Enable','on',...
        'String','edit parameters',...
        'HorizontalAlignment','left',...
        'Style','text');
   
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % get the variables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
    
    % specify way of calculating coherence
    methodGroup = uibuttongroup('visible','off',...
         'Units','normalized',...
        'Position',[0 0.3 1 0.6],...
        'Parent',centralPanel,...
        'Tag','makeStrfCohGUI_methodGroup');
    
    uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.01 0.9  0.98 0.15],...
        'Style','Text',...
        'String','averaging over',...
        'HandleVisibility','off',...
        'Tag','makeStrfCohGUI_methodGroupText',...
        'Enable','on');
    
    uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.1 0.71 0.8 0.18],...
        'Style','Radio',...
        'String','trials',...
        'HandleVisibility','off',...
        'Tag','makeStrfCohGUI_methodGroupTrials',...
        'Enable','on');
    windowsButton=uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.1 0.51 0.8 0.18],...
        'Style','Radio',...
        'String','sliding windows',...
        'HandleVisibility','off',...
        'Tag','makeStrfCohGUI_methodGroupWindows',...
        'Enable','on');
    uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.01 0.31 0.7 0.18],...
        'Style','Text',...
        'String','window size [ms]',...
        'Tag','makeStrfCohGUI_methodGroupWindowSizeText',...
        'Enable','on');
    uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.72 0.31 0.27 0.18],...
        'Style','edit',...
        'String','[3000]',...
        'Tag','makeStrfCohGUI_methodGroupWindowSize',...
        'Enable','on');

    
    uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.01 0.05 0.7 0.18],...
        'Style','Text',...
        'String','sliding steps [ms]',...
        'Tag','makeStrfCohGUI_methodGroupWindowSlideText',...
        'Enable','on');
    
        uicontrol('Parent',methodGroup,...
        'Units','normalized',...
        'Position',[0.72 0.05 0.27 0.18],...
        'Style','edit',...
        'String','[13]',...
        'Tag','makeStrfCohGUI_methodGroupWindowSlide',...
        'Enable','on');
    
    set(methodGroup,'SelectionChangeFcn',@selMethod_callback);
    set(methodGroup,'SelectedObject',[windowsButton]);  % Select one Default
    set(methodGroup,'UserData','windows'); % also set the userdata default
    set(methodGroup,'Visible','on');
    
        
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.01 0.15 0.4 0.1],...
        'Style','Text',...
        'String','entityIDs',...
        'Tag','makeStrfCohGUI_entityIDText',...
        'Enable','on');
    
        uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.45 0.15 0.4 0.1],...
        'Style','edit',...
        'String','[1:9]',...
        'Tag','makeStrfCohGUI_entityIDs',...
        'Enable','on');
    
    %%%%%% button to determine coherence %%%%%%%%
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.1    0.01    0.8  0.1],... 
        'Style','pushbutton',...
        'String','calculate coherence',...
        'Tag','makeStrfGwnGUI_coherencePushbutton',...
        'Enable','on',...
        'Callback',@determineCoherencePushbuttonCallback); 
    
    

catch
    %if error occurs here, the window is closed, the error is rethrown
    %    and then catched by the main window
    close(findobj('tag', ',makeStrfCohGUI'));
    rethrow(lasterror);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                 %%%% FUNCTIONS %%%%


function selMethod_callback(source,eventdata)
temp=get(get(source,'SelectedObject'),'String');
tmp=findobj('Tag','makeStrfCohGUI_methodGroup');
set(tmp,'UserData',temp);



    function determineCoherencePushbuttonCallback(a,b)
        global preferredOri linearPred normPredCoh expCoh F1 F2 type predCoh
        %parameters from the main makeStrfGUI
        selectedEvent=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedEventEntity']),'String'));
%parameters from this GUI
selectedEntities=str2num(get(findobj('Tag','makeStrfCohGUI_entityIDs'),'String'));
    tmp=findobj('Tag','makeStrfCohGUI_methodGroup');
    selectedMethod= get(tmp(1),'UserData');
    if strcmp('trials',selectedMethod)

        windowSize=0;
        windowShift=0;
    elseif strcmp('windows',selectedMethod)
  windowSize=str2num(get(findobj('Tag','makeStrfCohGUI_methodGroupWindowSize'),'String'));
  windowShift=str2num(get(findobj('Tag','makeStrfCohGUI_methodGroupWindowSlide'),'String'));
    end
        %  Boolean
sp=get(findobj('Tag','makeStrfCohGUI_sparseCheckbox'),'Value');
[normPredCoh,predCoh,expCoh,F1,F2]=predictedCoherence('linearPred',linearPred, 'neuralEntityIDs',selectedEntities,'eventEntityID',selectedEvent,'windowSize',windowSize,'windowShift',windowShift,'ifplot',1,'method',selectedMethod);
   