function makeStrfInfoGUI()

% GUI for analyzing some characteristics of the coding of the spike train.
%
%
%
% H. Walz Oct. 2008
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de
global nsFile;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;


try

    % Check if the sortSpikes GUI is already open
    if ishandle(findobj('tag', 'makeStrfInfoGUI'))
        close(findobj('tag', 'makeStrfInfoGUI'));
    end;

    % GUI window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=30;
    GUIheight=17;

    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','makeStrfInfoGUI', ...
        'Name','makeStrfInfoGUI',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'resize','off');

    % panels
    centralPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','makeStrfInfoGUI_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','makeStrfInfoGUI_messageBarPanel');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','makeStrfInfoGUI_messageBarText',...
        'Enable','on',...
        'String','edit parameters',...
        'HorizontalAlignment','left',...
        'Style','text');
   
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % get the variables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   
    
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.35    0.87    0.3    0.07],...
        'Style','text',...
        'String','delta ',...
        'Tag','makeStrfInfoGUI_selectedDeltaText',...
        'Enable','on');
    
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.3   0.79   0.4    0.07],...
        'Style','edit',...
        'String','[0.013]',...
        'Tag','makeStrfInfoGUI_selectedDeltaEdit',...
        'Enable','on');
   
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.35   0.7    0.3    0.07],...
        'Style','text',...
        'String','T',...
        'Tag','makeStrfInfoGUI_selectedTText',...
        'Enable','on');
    
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.3    0.62   0.4    0.07],...
        'Style','edit',...
        'String','[0.013]',...
        'Tag','makeStrfInfoGUI_selectedTEdit',...
        'Enable','on');
   
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.01   0.53    0.98    0.07],...
        'Style','text',...
        'String','repetitions of frames',...
        'Tag','makeStrfInfoGUI_selectedRepText',...
        'Enable','on');
    
    uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.3    0.45   0.4    0.07],...
        'Style','edit',...
        'String','[1]',...
        'Tag','makeStrfInfoGUI_selectedRepEdit',...
        'Enable','on');
    
 uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.1    0.1    0.8  0.1],... 
        'Style','pushbutton',...
        'String','calculate info',...
        'Tag','makeStrfInfoGUI_InfoPushbutton',...
        'Enable','on',...
        'Callback',@determineInfoPushbuttonCallback); 
  uicontrol('Parent',centralPanel,...
        'Units','normalized',...
        'Position',[0.2 0.3 0.6 0.08],...
        'Style','checkbox',...
        'String','Sparseness',...
        'Tag','makeStrfInfoGUI_sparseCheckbox',...
        'Enable','on');

catch
    %if error occurs here, the window is closed, the error is rethrown
    %    and then catched by the main window
    close(findobj('tag', ',makeStrfInfoGUI'));
    rethrow(lasterror);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                 %%%% FUNCTIONS %%%%


    function determineInfoPushbuttonCallback(a,b)
        global preferredOri Iss S kurt Ibin Isec Ispike Bias E type
        %parameters from the main makeStrfGUI
        selectedResponse=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedResponseEntities']),'String'));
trialDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedTrialDuration']),'String'));
baseDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedBaseDuration']),'String'));
nTrials=length(str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedEstimationTrials']),'String')));
frameDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedFrameDuration']),'String'));
%parameters from this GUI
selectedDelta=str2num(get(findobj('Tag','makeStrfInfoGUI_selectedDeltaEdit'),'String'));
selectedT=str2num(get(findobj('Tag','makeStrfInfoGUI_selectedTEdit'),'String'));
selectedRep=str2num(get(findobj('Tag','makeStrfInfoGUI_selectedRepEdit'),'String'));
%  Boolean
sp=get(findobj('Tag','makeStrfInfoGUI_sparseCheckbox'),'Value');
   

[Iss, S, kurt, Ibin, Isec,Ispike, Bias,E]=calculateInformation('analogEntityIDs',selectedResponse,'trialDurationT',trialDuration, 'frameDurationT',frameDuration,'delta',selectedDelta,'T',selectedT,'rep',selectedRep,'sparse',sp,'baseDuration',baseDuration,'preferredOri',preferredOri,'nTrials',nTrials);
disp('done calculating information measures')
