function makeStrf()
% GUI for calculating the spatiotemporal receptive field.
%
% here a couple of parameters and methods can be chosen
% used as UI to parameter value pair generation for the
% command line function sortSpikes.m
%
% H. Walz Feb 2008
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de


global nsFile;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;


try

    % Check if the sortSpikes GUI is already open
    if ishandle(findobj('tag', 'makeStrfGUI'))
        close(findobj('tag', 'makeStrfGUI'));
    end;

    % GUI window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=40;
    GUIheight=13;

    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','makeStrfGUI', ...
        'Name','make spatiotemporal RF GUI',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'resize','off');

    % panels
    centralPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','makeStrfGUI_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','makeStrf_messageBarPanel');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','makeStrfGUI_messageBarText',...
        'Enable','on',...
        'String','choose stimulus',...
        'HorizontalAlignment','left',...
        'Style','text');


    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[10 2 20 (BUTTON_HEIGHT)],...
        'Style','pushbutton',...
        'String','white noise',...
        'Tag','makeStrfGUI_GWNPushbutton',...
        'Enable','on',...
        'Callback',@makeStrfGWNPushbuttonCallback);


    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[10 5 20 (BUTTON_HEIGHT)],...
        'Style','pushbutton',...
        'String','drifting gratings',...
        'Tag','makeStrfGUI_DGPushbutton',...
        'Enable','on',...
        'Callback',@makeStrfDGPushbuttonCallback);


    uicontrol('Parent',centralPanel,...
        'Units','characters',...
        'Position',[10 8 20 (BUTTON_HEIGHT)],...
        'Style','pushbutton',...
        'String','natural images',...
        'Tag','makeStrfGUI_NIPushbutton',...
        'Enable','on',...
        'Callback',@makeStrfNIPushbuttonCallback);



catch
    % if error occurs here, the window is closed, the error is rethrown
    % and then catched by the main window
    close(findobj('tag', ',makeStrfGUI'));
    rethrow(lasterror);
end


%start GUIs for stimulus selection
function makeStrfGWNPushbuttonCallback(a,b)
global nsFile;

makeStrfGwnGUI;

function makeStrfDGPushbuttonCallback(a,b)
global nsFile;

makeStrfDgGUI;

function makeStrfNIPushbuttonCallback(a,b)
global nsFile;

makeStrfNIGUI;



