function makeStrfCodingGUI()

% GUI for analyzing some characteristics of the coding of the spike train.
%
%
%
% H. Walz Oct. 2008
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de
global nsFile;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;


try

    % Check if the sortSpikes GUI is already open
    if ishandle(findobj('tag', 'makeStrfCodingGUI'))
        close(findobj('tag', 'makeStrfCodingGUI'));
    end;

    % GUI window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=90;
    GUIheight=25;

    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','makeStrfCodingGUI', ...
        'Name','makeStrfCodingGUI',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'resize','off');

    % panels
    leftPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth/2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','makeStrfCodingGUI_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
    
    rightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth/2 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth/2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)],...
        'Tag','makeStrfCodingGUI_centralPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','makeStrfCodingGUI_messageBarPanel');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','makeStrfCodingGUI_messageBarText',...
        'Enable','on',...
        'String','calculate statistics of spike train',...
        'HorizontalAlignment','left',...
        'Style','text');
   
    
    %%% Buttons etc. %%%%%%%%%
    %%% calculate events?
    uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.01 0.9 0.8 0.08],...
        'Style','checkbox',...
        'String',' event-based measures',...
        'Tag','makeStrfCodingGUI_eventsCheckbox',...
        'Enable','on');

    % specify way of calculating the events
    eventGroup = uibuttongroup('visible','off',...
         'Units','normalized',...
        'Position',[0.1 0.6 0.7 0.25],...
        'Parent',leftPanel,...
        'Tag','makeStrfCodingGUI_eventGroup');
    
    uicontrol('Parent',eventGroup,...
        'Units','normalized',...
        'Position',[0.1  0.92 0.8 0.16],...
        'Style','Text',...
        'String','find events by',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_eventGroupText',...
        'Enable','on');
    
    threshButton=uicontrol('Parent',eventGroup,...
        'Units','normalized',...
        'Position',[0.01 0.71 0.98 0.18],...
        'Style','Radio',...
        'String','threshold',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_eventGroupThreshold',...
        'Enable','on');
    uicontrol('Parent',eventGroup,...
        'Units','normalized',...
        'Position',[0.3 0.47 0.4 0.23],...
        'Style','Edit',...
        'String','[0.3]',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_eventGroupThresholdFactor',...
        'Enable','on');
    baseLineButton=uicontrol('Parent',eventGroup,...
        'Units','normalized',...
        'Position',[0.01 0.25 0.98 0.18],...
        'Style','Radio',...
        'String','separating baseline',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_eventGroupBaselineText',...
        'Enable','on');
    
    uicontrol('Parent',eventGroup,...
        'Units','normalized',...
        'Position',[0.3 0.01 0.4 0.23],...
        'Style','Edit',...
        'String','[20]',...
        'Tag','makeStrfCodingGUI_eventGroupBaseline',...
        'Enable','on');
    
    
    set(eventGroup,'SelectionChangeFcn',@selEvent_callback);
    set(eventGroup,'SelectedObject',[baseLineButton]);  % Select one Default
    set(eventGroup,'UserData','baseLine'); % also set the userdata default
    set(eventGroup,'Visible','on');

    
    
 %%% calculate cross-correlation between trials ?
    uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.01 0.45 0.8 0.08],...
        'Style','checkbox',...
        'String',' xcorr-width between trials',...
        'Tag','makeStrfCodingGUI_xcorrCheckbox',...
        'Enable','on');
  uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.1 0.36 0.4 0.06],...
        'Style','Text',...
        'String','+/- cutouts',...
        'Tag','makeStrfCodingGUI_xcorrText',...
        'Enable','on');
    
        uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.55 0.36 0.25 0.06],...
        'Style','edit',...
        'String','[100]',...
        'Tag','makeStrfCodingGUI_xcorrEdit',...
        'Enable','on');
 
        
    %%% calculate Fano Factor in sliding windows?
    uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.01 0.2 0.87 0.08],...
        'Style','checkbox',...
        'String',' Fano Factor in sliding windows',...
        'Tag','makeStrfCodingGUI_fanoFactorCheckbox',...
        'Enable','on');
    
    %sliding windows text   
    uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.05 0.13 0.7 0.06],...
        'Style','Text',...
        'String','sizes of sliding windows [ms]',...
        'Tag','makeStrfCodingGUI_fanoFactorText',...
        'Enable','on');
           
    %sliding windows edit
    uicontrol('Parent',leftPanel,...
        'Units','normalized',...
        'Position',[0.01 0.04 0.98 0.08],...
        'Style','edit',...
        'String','[1,5,10,25,50,250,500,1000,3000]',...
        'Tag','makeStrfCodingGUI_fanoFactorEdit',...
        'Enable','on');
    

     %%% right panel %%%%%%%%%
    %%% calculate victor-measure?
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.01 0.9 0.8 0.08],...
        'Style','checkbox',...
        'String','victor-measure of distance',...
        'Tag','makeStrfCodingGUI_victorCheckbox',...
        'Enable','on');

    % specify way of calculating victor
    victorGroup = uibuttongroup('visible','off',...
         'Units','normalized',...
        'Position',[0.1 0.52 0.7 0.35],...
        'Parent',rightPanel,...
        'Tag','makeStrfCodingGUI_victorGroup');
    
    uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.1  0.95 0.8 0.1],...
        'Style','Text',...
        'String','grouping',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupText',...
        'Enable','on');
    
    allButton=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.01 0.79 0.98 0.15],...
        'Style','Radio',...
        'String',' all',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupAll',...
        'Enable','on');
    twoButton=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.01 0.62 0.98 0.15],...
        'Style','Radio',...
        'String',' two groups',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupTwo',...
        'Enable','on');
    
    xGroup=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.13 0.42 0.8 0.13],...
        'Style','Text',...
        'String','entityIDs of the groups',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupTwoXText',...
        'Enable','on');
        xGroup=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.13 0.27 0.35 0.15],...
        'Style','edit',...
        'String','x',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupTwoX',...
        'Enable','on');
    

    
        xGroup=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.53 0.27 0.35 0.15],...
        'Style','edit',...
        'String','y',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupTwoY',...
        'Enable','on');
    trialsButton=uicontrol('Parent',victorGroup,...
        'Units','normalized',...
        'Position',[0.01 0.01 0.8 0.2],...
        'Style','Radio',...
        'String',' trials',...
        'HandleVisibility','off',...
        'Tag','makeStrfCodingGUI_victorGroupTrials',...
        'Enable','on');
    
    
    set(victorGroup,'SelectionChangeFcn',@selVictor_callback);
    set(victorGroup,'SelectedObject',[trialsButton]);  % Select one Default
    set(victorGroup,'UserData','trials'); % also set the userdata default
    set(victorGroup,'Visible','on');
%%% cost parameters
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.04    0.45   0.2  0.06],... 
        'Style','Text',...
        'String','cost',...
        'Tag','makeStrfCodingGUI_costVictorText',...
        'Enable','on'); 
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.26   0.44    0.7  0.08],... 
        'Style','edit',...
        'String','[0.1,1,10,100,1000]',...
        'Tag','makeStrfCodingGUI_costVictor',...
        'Enable','on'); 
    
    %%% calculate correlation coefficient?
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.01 0.31 0.8 0.08],...
        'Style','checkbox',...
        'String','correlation coefficient',...
        'Tag','makeStrfCodingGUI_corrCoefCheckbox',...
        'Enable','on');
    
     %%% calculate inner product?
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.01 0.2 0.95 0.08],...
        'Style','checkbox',...
        'String','normalized mean inner product',...
        'Tag','makeStrfCodingGUI_innerProductCheckbox',...
        'Enable','on');
   
    
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.1    0.105    0.3  0.06],... 
        'Style','Text',...
        'String','entityIDs',...
        'Tag','makeStrfCodingGUI_selectedEntitiesText',...
        'Enable','on'); 
    uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.45    0.095    0.4  0.08],... 
        'Style','edit',...
        'String','[1:9]',...
        'Tag','makeStrfCodingGUI_selectedEntities',...
        'Enable','on'); 
    
     uicontrol('Parent',rightPanel,...
        'Units','normalized',...
        'Position',[0.2    0.01    0.6  0.08],... 
        'Style','pushbutton',...
        'String','calculate',...
        'Tag','makeStrfCodingGUI_runPushbutton',...
        'Enable','on',...
        'Callback',@runPushbuttonCallback); 
    
    
catch
    %if error occurs here, the window is closed, the error is rethrown
    %    and then catched by the main window
    close(findobj('tag', ',makeStrfCodingGUI'));
    rethrow(lasterror);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                 %%%% FUNCTIONS %%%%


% %% Get the grouping of the victor calculation
function selVictor_callback(source,eventdata)
% disp(get(get(source,'SelectedObject'),'String'));
temp=get(get(source,'SelectedObject'),'String');
tmp=findobj('Tag','makeStrfCodingGUI_victorGroup');
set(tmp,'UserData',temp);
                 

function selEvent_callback(source,eventdata)
% disp(get(get(source,'SelectedObject'),'String'));
temp=get(get(source,'SelectedObject'),'String');
tmp=findobj('Tag','makeStrfCodingGUI_eventGroup');
set(tmp,'UserData',temp);
                 
                 
function runPushbuttonCallback(a,b)
%%% get parameters
% from main GUI
global type rel relFrac Prec PrecFirst PrecHalf XcorrWidth CorrCoef FFevents FF nsFile
trialDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedTrialDuration']),'String'));
baseDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedBaseDuration']),'String'));
nTrials=length(str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedEstimationTrials']),'String')));
frameDuration=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedFrameDuration']),'String'));
selected_event=str2num(get(findobj('Tag',['makeStrf',type,'GUI_selectedEventEntity']),'String'));
% from this GUI
selectedEntities=str2num(get(findobj('Tag','makeStrfCodingGUI_selectedEntities'),'String'));
iT=get(findobj('Tag','makeStrfCodingGUI_eventsCheckbox'),'Value');
tmpE=findobj('Tag','makeStrfCodingGUI_eventGroup');
userStringEvent = get(tmpE(1),'UserData');
if strcmp(userStringEvent,'threshold')
    thresh=str2num(get(findobj('Tag','makeStrfCodingGUI_eventGroupThresholdFactor'),'String'));
elseif strcmp(userStringEvent,'baseLine')
    thresh=0;
    baseLine=str2num(get(findobj('Tag','makeStrfCodingGUI_eventGroupBaseline'),'String'));
end
if strcmp(type,'Dg')
    global preferredOri
    pOri=preferredOri;
else
    pOri=[];
end
iFF=get(findobj('Tag','makeStrfCodingGUI_fanoFactorCheckbox'),'Value');
if iFF
    timeWindows=str2num(get(findobj('Tag','makeStrfCodingGUI_fanoFactorEdit'),'String'));
else
    timeWindows=[];
end

iXC=get(findobj('Tag','makeStrfCodingGUI_xcorrCheckbox'),'Value');
cutout=str2num(get(findobj('Tag','makeStrfCodingGUI_xcorrEdit'),'String'));
iCC=get(findobj('Tag','makeStrfCodingGUI_corrCoefCheckbox'),'Value');
iRel=get(findobj('Tag','makeStrfCodingGUI_innerProductCheckbox'),'Value');
[rel,relFrac,Prec,PrecFirst,PrecHalf,XcorrWidth, CorrCoef,FFevents,FF]=calculateReliability('eventEntity',selected_event,'responseEntities',selectedEntities,'threshFactor',thresh,'preferredOri',pOri,'baseDuration',baseDuration,'trialDuration',trialDuration,'baseLine',baseLine,'ifplot',1,'timeWindows',timeWindows,...
    'events',iT,'width',iXC,'xcorrCut',cutout,'correlationCoefficient',iCC,'reliability',iRel,'fanoFactor',iFF,'nTrials',nTrials);

iV=get(findobj('Tag','makeStrfCodingGUI_victorCheckbox'),'Value');
if iV
    global d
    tmp=findobj('Tag','makeStrfCodingGUI_victorGroup');
    selected_grouping= get(tmp(1),'UserData');
    costs=str2num(get(findobj('Tag','makeStrfCodingGUI_costVictor'),'String'));
    if strcmp(selected_grouping,'two groups')
        y=str2num(get(findobj('Tag','makeStrfCodingGUI_victorGroupTwoY'),'String'));
        x=str2num(get(findobj('Tag','makeStrfCodingGUI_victorGroupTwoX'),'String'));
        d=calculateSpikeMetrics('x',x,'cost',costs,'trialDuration',trialDuration,'baseDuration',baseDuration,'ifplot',1,'y',y,'grouping',selected_grouping) ;
    else
        d=calculateSpikeMetrics('x',selectedEntities,'cost',costs,'trialDuration',trialDuration,'baseDuration',baseDuration,'ifplot',1,'grouping',selected_grouping) ;
    end
end
display('done calculating reliability measures');


