function detectSpikesGUI()
% GUI for operating the detectSpikes function.
%
% here a couple of parameters and methods can be chosen
% used as UI to parameter value pair generation for the
% command line function detectSpikes.m
%
% (0) R.Meier Feb 07, meier@biologie.uni-freiburg.de
% major modifications of GUI: MNJun07
%
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

global nsFile; %-% if needed.

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;

try

    % Check if the detectSpikes GUI is already open
    if ishandle(findobj('tag', 'detectSpikesGUI'))
        close(findobj('tag', 'detectSpikesGUI'));
    end;

    % GUI window
    %-% Values are suggestions for small window
    GUIxPos=20;
    GUIyPos=20;
    GUIwidth=70;
    GUIheight=20;

    % detectSpikesGUI - main window
    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth GUIheight], ...
        'Tag','detectSpikesGUI', ...
        'Name','Spike Detection GUI',...
        'MenuBar','none',...
        'NumberTitle','off',...
        'resize','off');

    % panels

    % upperLeftPanel
    upperLeftPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 (GUIheight)*.4 ...
        GUIwidth/2 (GUIheight)*.6],...
        'Tag','detectSpikesGUI_upperLeftPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    %upperRightPanel
    upperRightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth/2 (GUIheight)*.4...
        GUIwidth/2 (GUIheight)*.6],...
        'Tag','detectSpikesGUI_upperRightPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    %lowerLeftPanel
    lowerLeftPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth*.5 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)*.4],...
        'Tag','detectSpikesGUI_lowerLeftPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    %lowerRightPanel
    lowerRightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth*.5 MESSAGEBAR_PANEL_HEIGHT ...
        GUIwidth*.5 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)*.4],...
        'Tag','detectSpikesGUI_lowerRightPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);

    %messageBarPanel
    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','detectSpikesGUI_messageBarPanel');

    %NtimesTagEdit
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[1    2    15    BUTTON_HEIGHT],...
        'Style','edit',...
        'String','5',...
        'Tag','detectSpikesGUI_NtimesTagEdit',...
        'Enable','on');

    % thresFactorText - text label
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[1    4    15    BUTTON_HEIGHT],...
        'Style','text',...
        'String','thres. factor',...
        'Tag','detectSpikesGUI_thresFactorText',...
        'Enable','on');

    % get the Vector which Data Traces should be used
    % VectorAnalogDataEdit
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[17    2    15    BUTTON_HEIGHT],...
        'Style','edit',...
        'String','[1]',...
        'Tag','detectSpikesGUI_VectorAnalogDataEdit',...
        'Enable','on');
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[17    4    15    BUTTON_HEIGHT],...
        'Style','text',...
        'String','[EntityIDs]',...
        'Tag','detectSpikesGUI_dumbTxt',...
        'Enable','on');

    % pre cutout time
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[1    7    15    BUTTON_HEIGHT],...
        'Style','edit',...
        'String','0.001',...
        'Tag','detectSpikesGUI_preCut_ms_Edit',...
        'Enable','on');
      uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[1    9    15    BUTTON_HEIGHT],...
        'Style','text',...
        'String','Pre Trigger [s]',...
        'Tag','detectSpikesGUI_dumbTxt',...
        'Enable','on');

  % post cutout time
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[17    7   16    BUTTON_HEIGHT],...
        'Style','edit',...
        'String','0.002',...
        'Tag','detectSpikesGUI_postCut_ms_Edit',...
        'Enable','on');
    uicontrol('Parent',upperLeftPanel,...
        'Units','characters',...
        'Position',[17    9    16    BUTTON_HEIGHT],...
        'Style','text',...
        'String','Post Trigger [s]',...
        'Tag','detectSpikesGUI_dumbTxt',...
        'Enable','on');


    %%%% Spike Detection Method Selection Radio Group

    radioGroup = uibuttongroup('visible','off'...
        ,'Units','characters',...
        'Position',[1 1 GUIwidth/2-3 (GUIheight)*.6-1.5],...
        'Parent',upperRightPanel,...
        'Tag','detectSpikesGUI_radioGroup',...
        'Title','Detection Method');

    radioButton1 = uicontrol('Style','Radio',...
        'String','1) rect. N * Median',...
        'Units','characters',...
        'pos',[.5 7.75 23 BUTTON_HEIGHT],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_radioButton1');

    radioButton2 = uicontrol('Style','Radio',...
        'String','2) rect. Mean + N*SD',...
        'Units','characters',...
        'pos',[.5 6.5 27 BUTTON_HEIGHT],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_radioButton2');

    radioButton3 = uicontrol('Style','Radio',...
        'String','3) Mean + N*SD',...
        'Units','characters',...
        'pos',[.5 5.25 23 BUTTON_HEIGHT],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_radioButton3');

    radioButton4 = uicontrol('Style','Radio',...
        'String','4) with known [median]',...
        'Units','characters',...
        'pos',[.5 4 27 BUTTON_HEIGHT],...
        'parent',radioGroup,...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_radioButton4');

    %median tag
    uicontrol('Parent',radioGroup,...
        'Units','characters',...
        'Position',[4    3   20    BUTTON_HEIGHT-0.25],...
        'Style','edit',...
        'String','[20]',...
        'Tag','detectSpikesGUI_median',...
        'Enable','on');
    
    %which polarity
    polarityGroup = uibuttongroup('visible','off',...
         'Units','characters',...
        'Position',[1 1.5 GUIwidth/2-3 BUTTON_HEIGHT],...
        'Parent',upperRightPanel,...
        'Tag','detectSpikesGUI_polarityGroup');
    
    uicontrol('Parent',polarityGroup,...
        'Units','characters',...
        'Position',[2.5   1   12    BUTTON_HEIGHT],...
        'Style','Text',...
        'String','detection on',...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_Text',...
        'Enable','on');
    
    negButton=uicontrol('Parent',polarityGroup,...
        'Units','characters',...
        'Position',[0    0    12    BUTTON_HEIGHT],...
        'Style','Radio',...
        'String','negative',...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_negative',...
        'Enable','on');
    
    posButton=uicontrol('Parent',polarityGroup,...
        'Units','characters',...
        'Position',[12    0    12    BUTTON_HEIGHT],...
        'Style','Radio',...
        'String','positive',...
        'HandleVisibility','off',...
        'Tag','detectSpikesGUI_positive',...
        'Enable','on');
    
    absButton=uicontrol('Parent',polarityGroup,...
        'Units','characters',...
        'Position',[23  0     8   BUTTON_HEIGHT],...
        'Style','Radio',...
        'HandleVisibility','on',...
        'String','both',...
        'Tag','detectSpikesGUI_absolute',...
        'Enable','on');



    set(radioGroup,'SelectionChangeFcn',@selMethod_callback);
    set(radioGroup,'SelectedObject',[radioButton1]);  % Select one Default
    set(radioGroup,'UserData','1) rect. N * Median'); % also set the userdata default
    set(radioGroup,'Visible','on');
    
    set(polarityGroup,'SelectionChangeFcn',@selPolarity_callback);
    set(polarityGroup,'SelectedObject',[negButton]);  % Select one Default
    set(polarityGroup,'UserData','negative'); % also set the userdata default
    set(polarityGroup,'Visible','on');

    %%%% Checkbox -> make Cutouts and Plot them
    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[1    3    16    BUTTON_HEIGHT],...
        'Style','checkbox',...
        'String','Cutouts',...
        'Tag','detectSpikesGUI_cutOutsCheckbox',...
        'Enable','on');

    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[1    1   16    BUTTON_HEIGHT],...
        'Style','checkbox',...
        'String','SpikeSorting',...
        'Tag','detectSpikesGUI_spikeSortingCheckbox',...
        'Enable','on');


    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[1    5   16    BUTTON_HEIGHT],...
        'Style','checkbox',...
        'String','showSpikes',...
        'Tag','detectSpikesGUI_showSpikesCheckbox',...
        'Enable','on');
    
    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[19    5   14    BUTTON_HEIGHT],...
        'Style','checkbox',...
        'String','dead time',...
        'Tag','detectSpikesGUI_deadTimeCheckbox',...
        'Enable','on');
    %dead time tag
    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[19    3    14    BUTTON_HEIGHT],...
        'Style','edit',...
        'String','[0.002]',...
        'Tag','detectSpikesGUI_deadTime',...
        'Enable','on');


    % text label
    uicontrol('Parent',lowerLeftPanel,...
        'Units','characters',...
        'Position',[.5    .25  GUIwidth*.5-2 (GUIheight-MESSAGEBAR_PANEL_HEIGHT)*.4-.75],...
        'Style','listbox',...
        'String','Spike Det. Results',...
        'Tag','detectSpikesGUI_SpikeDetectionResultsListbox',...
        'Enable','on');

    % message bar
    messageBarPanelPos=get(messageBarPanel,'Position');
    messageBar=uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','detectSpikesGUI_messageBarText',...
        'Enable','on',...
        'String','',...
        'HorizontalAlignment','left',...
        'Style','text');

    % button to run the tool
    uicontrol('Parent',lowerRightPanel,...
        'Units','characters',...
        'Position',[22 1 11 BUTTON_HEIGHT],...
        'Style','pushbutton',...
        'String','RUN',...
        'Tag','detectSpikesGUI_detectSpikesPushbutton',...
        'Enable','on',...
        'Callback',@detectSpikesPushbuttonCallback);
    %-% use {@myCallback,arg1,arg2,...} to have args

catch
    % if error occurs here, the window is closed, the error is rethrown
    % and then caught by the main window
    close(findobj('tag', 'detectSpikesGUI'));
    rethrow(lasterror);
end

%%% FUNCTIONS

function detectSpikesPushbuttonCallback(source,event)
% Run tool button callback; starts detectSpikes.
% Source and event args are generated by default.
global nsFile; %-% if needed
try
    % posting 'busy' message
    postMessage('Busy - please wait...');

    %%%%%% Here: The Detection Starts now: Mean + N Times STD
    disp('starting spike-detection');
    %%% gather the values from all the
    %%% buttons in the figure !

    % Which Data Vectors
    tmp=findobj('Tag','detectSpikesGUI_VectorAnalogDataEdit');
    userString =get(tmp(1),'String'); % use first VALUE IF MULTIPLE FIGURES ARE OPEN
    % disp(userString) %% DEBUG
    selected_Data_Vectors=str2num((userString));

    % Adjustment Factor
    tmp=findobj('Tag','detectSpikesGUI_NtimesTagEdit');
    userString = get(tmp(1),'string');
    selected_ThresholdFactor=str2num(char(userString));

    %% Get the Value from the Radio Button-Group
    tmp=findobj('Tag','detectSpikesGUI_radioGroup');
    userString = get(tmp(1),'UserData');
    selected_method_Number=str2num(userString(1));

    %% Get the Value from the polarity Button-Group
    tmp=findobj('Tag','detectSpikesGUI_polarityGroup');
    selected_polarity= get(tmp(1),'UserData');

    
    % get the known median
    tmp=findobj('Tag','detectSpikesGUI_median');
    userString = get(tmp(1),'string');
    known_median=str2num(char(userString));


    %%% get the Cutout Checkbox value
    tmp=findobj('Tag','detectSpikesGUI_cutOutsCheckbox');
    make_CUTOUTS=get(tmp,'Value'); % DEFINE BOOL

    tmp=findobj('Tag','detectSpikesGUI_spikeSortingCheckbox');
    do_SPIKESORTING=get(tmp,'Value'); % DEFINE BOOL

    tmp=findobj('Tag','detectSpikesGUI_showSpikesCheckbox');
    show_SPIKES=get(tmp,'Value'); % DEFINE BOOL
    
    tmp=findobj('Tag','detectSpikesGUI_deadTimeCheckbox');
    do_deadTime=get(tmp,'Value'); % DEFINE BOOL
    
    tmp=findobj('Tag','detectSpikesGUI_deadTime');
    dTime=get(tmp(1),'string');
    deadTime=str2num(dTime);
    


    
    if do_SPIKESORTING==1 && make_CUTOUTS==0
        disp('Spike Sorting without Cutouts is impossible -> adding Cutouts!');
        make_CUTOUTS=1;
    end

    if do_SPIKESORTING==1
        disp('kmeans clustering is used for Spike sorting');
    end
    
    %%% get the PRE Trigger Cutout Time
    tmp=findobj('Tag','detectSpikesGUI_preCut_ms_Edit');
    PRE_MS=str2num(get(tmp,'String'));

    %%% get the POST Trigger Cutout Time
    tmp=findobj('Tag','detectSpikesGUI_postCut_ms_Edit');
    POST_MS=str2num(get(tmp,'String'));

    %% DEBUG
    %disp(['Ntimes='  num2str(selected_ThresholdFactor)]);
    %disp(['Vectors='  num2str(selected_Data_Vectors)]);

    %%% Start the Spike_detection Function
    txt_array=detectSpikes('analogEntityIndices',selected_Data_Vectors,...
        'thresholdFactor', selected_ThresholdFactor,...
        'methodNumber',selected_method_Number,...
        'knownMedian', known_median,...
        'SpikeSorting',do_SPIKESORTING,...
        'makeCutouts', make_CUTOUTS,...
        'showSpikes', show_SPIKES,...
        'selectDeadTime',do_deadTime,...
        'deadTime',deadTime,...
        'cutBefore',PRE_MS,...
        'cutAfter',POST_MS,...
       'polarity', selected_polarity);

    %% Generate a Spike Detection TEXTUAL REPORT
    %%% Write some summary to the GUI

    tmp=findobj('Tag','detectSpikesGUI_SpikeDetectionResultsListbox');
    set(tmp,'String',txt_array);
    %-% some checks maybe here?


    postMessage('...done.');
catch
    handleError(lasterror);
end

% %% Get the Spike Detection Method chosen via radiobuttion-changefunction
function selMethod_callback(source,eventdata)
% disp(get(get(source,'SelectedObject'),'String'));
temp=get(get(source,'SelectedObject'),'String');
tmp=findobj('Tag','detectSpikesGUI_radioGroup');
set(tmp,'UserData',temp);

% %% Get the polarity
function selPolarity_callback(source,eventdata)
% disp(get(get(source,'SelectedObject'),'String'));
temp=get(get(source,'SelectedObject'),'String');
tmp=findobj('Tag','detectSpikesGUI_polarityGroup');
set(tmp,'UserData',temp);

