% script makepulldownmenu generates the pulldown menus for browseEntitiesGUI.
%
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

set(myguiprops.mygui,'MenuBar','none');

% ---------------------------------------------
% help
helpmenu=uimenu('Parent',myguiprops.mygui,...
    'Label','&Help');

helploadingmcdfiles=uimenu('Parent',helpmenu,...
    'Label','What?',...
    'Callback','disp(''not yet available'')');
% ---------------------------------------------
% display
displaymenu=uimenu('Parent',myguiprops.mygui,...
    'Label','&Display');

opendisplaygui=uimenu('Parent',displaymenu,...
    'Label','display options',...
    'Callback','setEntityDisplayOptions');

% ---------------------------------------------
% selection
selectionmenu=uimenu('Parent',myguiprops.mygui,...
    'Label','&Selection');

enterselectionpulldown=uimenu('Parent',selectionmenu,...
    'Label','Enter selection',...
    'Callback','selectionctrl(''manual'')');

myseparator0=uimenu('Parent',selectionmenu,...
    'Label','-------------------',...
    'enable','off');

exportselectionpulldown=uimenu('Parent',selectionmenu,...
    'Label','Export Selection',...
    'Callback','selectionctrl(''export'')');

importselectionpulldown=uimenu('Parent',selectionmenu,...
    'Label','Import Selection',...
    'Callback','selectionctrl(''import'')');

myseparator1=uimenu('Parent',selectionmenu,...
    'Label','-------------------',...
    'enable','off');

selectallpulldown=uimenu('Parent',selectionmenu,...
    'Label','Select all',...
    'Callback','selectionctrl(''selectall'')');

unselectallpulldown=uimenu('Parent',selectionmenu,...
    'Label','Unselect all (clear)',...
    'Callback','selectionctrl(''unselectall'')');

myseparator2=uimenu('Parent',selectionmenu,...
    'Label','-------------------',...
    'enable','off');

selectpagepulldown=uimenu('Parent',selectionmenu,...
    'Label','Select page',...
    'Callback','selectionctrl(''selectpage'')');

unselectpagepulldown=uimenu('Parent',selectionmenu,...
    'Label','Unselect page',...
    'Callback','selectionctrl(''unselectpage'')');

myseparator3=uimenu('Parent',selectionmenu,...
    'Label','-------------------',...
    'enable','off');

invertallpulldown=uimenu('Parent',selectionmenu,...
    'Label','Invert whole selection',...
    'Callback','selectionctrl(''invertall'')');

unselectpagepulldown=uimenu('Parent',selectionmenu,...
    'Label','Invert page selection',...
    'Callback','selectionctrl(''invertpage'')');

% ---------------------------------------------
% filter
filtermenu=uimenu('Parent',myguiprops.mygui,...
    'Label','&Filter');

filtersettingspulldown=uimenu('Parent',filtermenu,...
    'Label','Filter settings',...
    'Callback',@filtersettingspulldowncallback);

% ---------------------------------------------
% Data
datamenu=uimenu('Parent',myguiprops.mygui,...
    'Label','&Data');

loadselecteddatapulldown=uimenu('Parent',datamenu,...
    'Label','Load selected entities',...
    'Callback',@loadselecteddatacallback);

loadfilterdatapulldown=uimenu('Parent',datamenu,...
    'Label','Load displayed entities',...
    'Callback',@loadfilterdatacallback);

showselecteddatapulldown=uimenu('Parent',datamenu,...
    'Label','Preview selected entities',...
    'Callback','showdata(''selectedentities'',1)');


