% PSTH_GUI(varargin)
% script to set PSTH GUI in basicProcessingGUI

set(radioGroup,'SelectedObject',[radioButtonPSTH]);
set(radioGroup,'UserData','PSTH');

headline_txt1=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[5   26   65    LABEL_HEIGHT*1.2],...
    'Style','text',...
    'String','define parameters for PSTH',...
    'Tag','headline1_txt',...
    'FontWeight','bold',...
    'Enable','on');
headline_txt2=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[5   24    65    LABEL_HEIGHT*2],...
    'Style','text',...
    'String',{['(requires spikes; if spikes are unsorted or neural data, unified UnitID assumed )']},...
    'Tag','headline2_txt',...
    'FontWeight','normal',...
    'Enable','on');


% segment or neural entityIDs
EntityID_texthandle=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2 21.5 30 LABEL_HEIGHT],...
    'Style','text',...
    'String','Neural / Segment EntityIDs :',...
    'Tag','dataID_txt',...
    'Enable','on');
EntityID_edit=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 21.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[1]',...
    'Tag','dataID_edit',...
    'Enable','on');

% define binSize
KernelSize_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2 19.5 30 LABEL_HEIGHT],...
    'Style','text',...
    'String','Kernel- (std) / Binsize [s] :',...
    'Tag','KernelSize_txt',...
    'Enable','on');
KernelSize=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 19.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0.01]',...
    'Tag','KernelSize_Edit',...
    'Enable','on');

% radioButtonGroup normalisation
radioGroup2 = uibuttongroup('visible','off',...
    'Units','characters',...
    'Position',[2 15.5 30 LABEL_HEIGHT*2.5],...
    'Parent',rightPanel,...
    'Tag','normSelectionGUI_radioGroup2',...
    'Title','Normalisation');

radioButtonRate = uicontrol('Style','Radio',...
    'String','Rate',...
    'Units','characters',...
    'pos',[1 0.3 10 BUTTON_HEIGHT],...
    'parent',radioGroup2,...
    'HandleVisibility','off',...
    'Tag','normSelectionGUI_radioGroupRate');

radioButtonNormal = uicontrol('Style','Radio',...
    'String','normalised',...
    'Units','characters',...
    'pos',[12 0.3 17 BUTTON_HEIGHT],...
    'parent',radioGroup2,...
    'HandleVisibility','off',...
    'Tag','normSelectionGUI_radioGroupNormal');

set(radioGroup2,'SelectionChangeFcn',@selectNorm_callback);
set(radioGroup2,'SelectedObject',[radioButtonRate]);
set(radioGroup2,'UserData','Rate');
set(radioGroup2,'Visible','on');

% radioButtonGroup kernel
radioGroup3 = uibuttongroup('visible','off',...
    'Units','characters',...
    'Position',[52 12.2 26 LABEL_HEIGHT*10],...
    'Parent',rightPanel,...
    'Tag','kernelSelectionGUI_radioGroup3',...
    'Title','binning');

subheadline1_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[54.5 18.5 15 BUTTON_HEIGHT],...
    'Style','text',...
    'String','sliding window',...
    'Tag','subheadline1_txt',...
    'Enable','on');

radioButtonBIN = uicontrol('Style','Radio',...
    'String','BIN',...
    'Units','characters',...
    'pos',[12 8.2 10 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupBIN');

radioButtonBOX = uicontrol('Style','Radio',...
    'String','BOX',...
    'Units','characters',...
    'pos',[0.5 4.7 10 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupBOX');

radioButtonTRI = uicontrol('Style','Radio',...
    'String','TRI',...
    'Units','characters',...
    'pos',[12 4.7 10 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupTRI');

radioButtonGAU = uicontrol('Style','Radio',...
    'String','GAU',...
    'Units','characters',...
    'pos',[0.5 3.2 10 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupGAU');

radioButtonEPA = uicontrol('Style','Radio',...
    'String','EPA',...
    'Units','characters',...
    'pos',[12 3.2 10 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupEpa');

radioButtonEXPr = uicontrol('Style','Radio',...
    'String','EXP (1)',...
    'Units','characters',...
    'pos',[0.5 1.7 14 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupEXP');

radioButtonEXPl = uicontrol('Style','Radio',...
    'String','EXP (-1)',...
    'Units','characters',...
    'pos',[12 1.7 13 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupEXP');

radioButtonALPr = uicontrol('Style','Radio',...
    'String','ALP (1)',...
    'Units','characters',...
    'pos',[0.5 0.2 14 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupALP');

radioButtonALPl = uicontrol('Style','Radio',...
    'String','ALP (-1)',...
    'Units','characters',...
    'pos',[12 0.2 13 BUTTON_HEIGHT],...
    'parent',radioGroup3,...
    'HandleVisibility','off',...
    'Tag','kernelSelectionGUI_radioGroupALP');

set(radioGroup3,'SelectionChangeFcn',@selectKernel_callback);
set(radioGroup3,'SelectedObject',[radioButtonBIN]);
set(radioGroup3,'UserData','BIN');
set(radioGroup3,'Visible','on');

subinfo_txt2=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2  10.5    45    BUTTON_HEIGHT*1.5],...
    'Style','text',...
    'String',{['If EventID or TriggerNr is empty overview histogram for every NeuralID is plotted']},...
    'Tag','subinfo_txt2',...
    'Enable','on');

% trigger / event entity
EntityID_texthandle=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2 8.5 30 LABEL_HEIGHT],...
    'Style','text',...
    'String','Event EntityID :',...
    'Tag','eventID_txt',...
    'Enable','on');
EntityID_edit=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 8.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[]',...
    'Tag','eventID_edit',...
    'Enable','on');

% select single triggers
TriggerNr_texthandle=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[12 6.5 20 LABEL_HEIGHT],...
    'Style','text',...
    'String','TriggerNr :',...
    'Tag','triggerNr_txt',...
    'Enable','on');
TriggerNr_edit=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 6.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[]',...
    'Tag','triggerNr_edit',...
    'Enable','on');

% pre and post trigger time
preTrig_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[12 4.5 20 LABEL_HEIGHT],...
    'Style','text',...
    'String','Pre Trigger [s] :',...
    'Tag','preTrig_txt',...
    'Enable','on');
preTrig=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 4.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0.01]',...
    'Tag','preTrig_Edit',...
    'Enable','on');
postTrig_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[12 2.5 20 LABEL_HEIGHT],...
    'Style','text',...
    'String','Post Trigger [s] :',...
    'Tag','postTrig_txt',...
    'Enable','on');
postTrig=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 2.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0.1]',...
    'Tag','postTrig_Edit',...
    'Enable','on');


% Run button
uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[57 1 20 BUTTON_HEIGHT*1.5],...
    'Style','pushbutton',...
    'String','RUN',...
    'Tag','rasterPSTH_RUN_GUIpushbutton',...
    'Enable','on',...
    'Callback',@PSTH_Callback);
