function myguiprops=queryEntitiesGUI(myguiprops)
% GUI for setting filter options. Called by browseEntitiesGUI.
% Filter settings are stored in FIND_GUIdata.filterSpecs.
%
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

% check if already open
if ishandle(findobj('tag', 'queryEntitiesGUI'))
    close(findobj('tag', 'queryEntitiesGUI'));
end;

%list of popupmenu choices - be sure to add new options at the END, to
%avoid mixup of indices.
propoptionlist={'no prop','all','event','analog','neural','segment','even','selected'};
conlist={'AND','EXCLUDE'};

%main window
queryEntitiesGUI=figure('Units','normalized',...
    'Position',[.2 .1 .3 .2], ...
    'Tag','queryEntitiesGUI', ...
    'Name','Filter settings',...
    'NumberTitle','off',...
    'MenuBar','none');

% general controls

%load filterspecs

loadfilterspecspushbutton=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.7    0.585    0.2   0.08],...
    'Tag','loadfilterspecspushbutton',...
    'Enable','on',...
    'String','Load filterSpecs',...
    'Callback',@loadfilterspecspushbuttoncallback,...
    'Style','Pushbutton');

%load filterspecs

savefilterspecspushbutton=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.7    0.455    0.2   0.08],...
    'Tag','savefilterspecspushbutton',...
    'Enable','on',...
    'String','Save filterSpecs',...
    'Callback',@savefilterspecspushbuttoncallback,...
    'Style','Pushbutton');

%apply filterspecs

applyfilterspecspushbutton=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.7    0.715    0.2   0.08],...
    'Tag','applyfilterspecspushbutton',...
    'Enable','on',...
    'String','Apply filterSpecs',...
    'Callback',@applyfilterspecspushbuttoncallback,...
    'Style','Pushbutton');

%reset filterspecs

resetfilterspecspushbutton=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.7    0.325    0.2   0.08],...
    'Tag','resetfilterspecspushbutton',...
    'Enable','on',...
    'String','Reset filterSpecs',...
    'Callback',@resetfilterspecspushbuttoncallback,...
    'Style','Pushbutton');

% actual filter setting controls

%

inverttextbox=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.29    0.85     0.1     0.045],...
    'Tag','inverttextbox',...
    'Enable','on',...
    'Style','text',...
    'String','Invert?');

prop1invertcheckbox=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.32    0.73    0.033   0.055],...
    'Tag','prop1invertcheckbox',...
    'Enable','on',...
    'Style','checkbox');

% filter choice 1

prop1optionspopup=uicontrol('Parent',queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.4 0.7 0.25 0.1],...
    'Tag','prop1optionspopup',...
    'String',propoptionlist(2:end),...
    'Style','popupmenu');

prop2invertcheckbox=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.32    0.45    0.033   0.055],...
    'Tag','prop2invertcheckbox',...
    'Enable','on',...
    'Style','checkbox');

% filter choice 2

prop2optionspopup=uicontrol('Parent',queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.4 0.42 0.25 0.1],...
    'Tag','prop2optionspopup',...
    'String',propoptionlist,...
    'Style','popupmenu');

prop3invertcheckbox=uicontrol('Parent', queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.32    0.17    0.033   0.055],...
    'Tag','prop3invertcheckbox',...
    'Enable','on',...
    'Style','checkbox');

% filter choice 3

prop3optionspopup=uicontrol('Parent',queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.4 0.14 0.25 0.1],...
    'Tag','prop3optionspopup',...
    'String',propoptionlist,...
    'Style','popupmenu');

con12popup=uicontrol('Parent',queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.11 0.42 0.15 0.1],...
    'Tag','con12popup',...
    'String',conlist,...
    'Style','popupmenu');

con23popup=uicontrol('Parent',queryEntitiesGUI,...
    'Units','normalized',...
    'Position',[0.11 0.14 0.15 0.1],...
    'Tag','con23popup',...
    'String',conlist,...
    'Style','popupmenu');

FIND_GUIdata=get(findobj('Tag','FIND_GUI'),'UserData');



function applyfilterspecspushbuttoncallback(a,b)

global nsFile;

% read filter settings from GUI
filterstring=loadquery;

% write filter settings to FIND_GUIdata
FIND_GUIdata=get(findobj('Tag','FIND_GUI'),'UserData');
FIND_GUIdata.filterSpecs=filterstring;
set(findobj('Tag','FIND_GUI'),'UserData',FIND_GUIdata);


%call browseEntitiesGUI, where filter settings are read from the main GUI.
browseEntitiesGUI();

function savefilterspecspushbuttoncallback(a,b)

% read filter settings from GUI
filterstring=loadquery;

%open putfile interface
FIND_GUIdata=get(findobj('Tag','FIND_GUI'),'UserData');
[savefilename,savefilepath,filterspec]=uiputfile({'*.mat','Matlab variable'});

%do nothing if file selection is cancelled
if filterspec==0;return;end

%filterstring is saved as a human readable .mat variable
tempstring=['save ','''',savefilepath,savefilename,'''',' filterstring'];
eval(tempstring);
disp(['filtersettings have been saved to ',savefilename])

function loadfilterspecspushbuttoncallback(a,b)
%loads filter settings from .mat file

%open getfile interface
[loadfilename,loadfilepath,filterspec]=uigetfile({'*.mat','Matlab variable'});
tempstring=['load ','''',loadfilepath,loadfilename,'''',' filterstring'];
eval(tempstring)
filterstring;
row=1;

%list of legal options - (note: this should be changed to be read from
%filter GUI!)
propoptionlist={'no prop','all','event','analog','neural','segment','even','selected'};
invertchecked=0;

%cycle through filterstring and set filterproperties directly in the GUI
for ii=1:length(filterstring)
    if strmatch(filterstring{ii},propoptionlist,'exact')    
        popupvalue=strmatch(filterstring{ii},propoptionlist,'exact');
        if row==1
            popupvalue=popupvalue-1;
        end
        tempstr=['prop',num2str(row),'optionspopup'];

        set(findobj(gcbf,'Tag',tempstr),'Value',popupvalue);

        if ~(invertchecked==1)
            tempstr=['prop',num2str(row),'invertcheckbox'];
            set(findobj(gcbf,'Tag',tempstr),'Value',0);
        end
        invertchecked=0;
        row=row+1;
    elseif strmatch(filterstring{ii},'INV')
        tempstr=['prop',num2str(row),'invertcheckbox'];
        set(findobj(gcbf,'Tag',tempstr),'Value',1);
        invertchecked=1;
    elseif strmatch(filterstring{ii},{'AND','EXCLUDE'})
        if row==2
            set(findobj(gcbf,'Tag','con12popup'),'Value',strmatch(filterstring{ii},{'AND','EXCLUDE'}))
        elseif row==3
            set(findobj(gcbf,'Tag','con23popup'),'Value',strmatch(filterstring{ii},{'AND','EXCLUDE'}))
        end
    end
end



function resetfilterspecspushbuttoncallback(a,b)
%resets filter settings to default settings

resetdlg=questdlg('Are you sure you want to reset all filter settings?',...
    'Reset filter settings',...
    'Yes','No','No');
switch resetdlg
    case 'Yes'
        set(findobj(gcbf,'Tag','prop1invertcheckbox'),'Value',0)
        set(findobj(gcbf,'Tag','prop1optionspopup'),'Value',1)
        set(findobj(gcbf,'Tag','con12popup'),'Value',1)
        set(findobj(gcbf,'Tag','prop2invertcheckbox'),'Value',0)
        set(findobj(gcbf,'Tag','prop2optionspopup'),'Value',1)
        set(findobj(gcbf,'Tag','con23popup'),'Value',1)
        set(findobj(gcbf,'Tag','prop3invertcheckbox'),'Value',0)
        set(findobj(gcbf,'Tag','prop3optionspopup'),'Value',1)
    otherwise
end











