% raterPlotGUI(varargin)
% script to set rasterPlot GUI in basicProcessingGUI

set(radioGroup,'SelectedObject',[radioButtonRaster]);  % Select one Default
set(radioGroup,'UserData','rasterPlot'); % also set the userdata default

headline_txt1=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[5   26    65    LABEL_HEIGHT*1.3],...
    'Style','text',...
    'String','define parameters for ploting',...
    'Tag','headline1_txt',...
    'FontWeight','bold',...
    'Enable','on');
headline_txt2=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[5   25    65    LABEL_HEIGHT],...
    'Style','text',...
    'String',['(requires spikes and event timestamps (trigger))'],...
    'Tag','headline2_txt',...
    'FontWeight','normal',...
    'Enable','on');

% pre and post trigger time
preTrig_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[12 17.5 20 LABEL_HEIGHT],...
    'Style','text',...
    'String','Pre Trigger [s] :',...
    'Tag','preTrig_txt',...
    'Enable','on');
preTrig=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[12 16 20 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0.01]',...
    'Tag','preTrig_Edit',...
    'Enable','on');
postTrig_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 17.5 20 LABEL_HEIGHT],...
    'Style','text',...
    'String','Post Trigger [s] :',...
    'Tag','postTrig_txt',...
    'Enable','on');
postTrig=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 16 20 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0.1]',...
    'Tag','postTrig_Edit',...
    'Enable','on');

EntityID_edit=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 20.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[1]',...
    'Tag','eventID_edit',...
    'Enable','on');

subinfo_txt=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[45  10.5    33    LABEL_HEIGHT*2],...
    'Style','text',...
    'String',{['(if spikes are unsorted or neural data, unified UnitID assumed )']},...
    'Tag','subinfo_txt',...
    'Enable','on');

% segment or neural entityIDs
EntityID_texthandle=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2 22.5 30 LABEL_HEIGHT],...
    'Style','text',...
    'String','Neural / Segment EntityIDs :',...
    'Tag','dataID_txt',...
    'Enable','on');
EntityID_edit=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[35 22.5 15 LABEL_HEIGHT],...
    'Style','edit',...
    'String','[1]',...
    'Tag','dataID_edit',...
    'Enable','on');

% trigger / event entity
EntityID_texthandle=uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[2 20.5 30 LABEL_HEIGHT],...
    'Style','text',...
    'String','Event EntityID :',...
    'Tag','eventID_txt',...
    'Enable','on');

% Run button
uicontrol('Parent',rightPanel,...
    'Units','characters',...
    'Position',[16 11 25 BUTTON_HEIGHT],...
    'Style','pushbutton',...
    'String','RUN',...
    'Tag','rasterPSTH_RUN_GUIpushbutton',...
    'Enable','on',...
    'Callback',@rasterPlot_Callback);