function selectmanual()
% Allows the user to enter entityIDs for manual selection in a vectorized form.
%
% Markus Nenniger 06
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

if ishandle(findobj('tag', 'entermanual'))
    close(findobj('tag', 'entermanual'));
end;

enterselection=figure('Units','normalized',...
    'Position',[.65 .7 .2 .1], ...
    'Tag','entermanual', ...
    'Name','Enter selection Manually',...
    'MenuBar','none');

selectinfobox=uicontrol('Parent',enterselection,...
    'Units','normalized',...
    'Position',[0.08    0.69    0.2    0.1],...
    'Tag','selectinfobox',...
    'Enable','on',...
    'String','Select:',...
    'Style','text');

selecteditbox=uicontrol('Parent',enterselection,...
    'Units','normalized',...
    'Position',[0.35    0.65    0.6    0.185],...
    'Tag','selecteditbox',...
    'Enable','on',...
    'Style','edit',...
    'BackgroundColor','w',...
    'TooltipString','enter EntityIDs to be selected',...
    'Callback',@selecteditboxcallback);

deselectinfobox=uicontrol('Parent',enterselection,...
    'Units','normalized',...
    'Position',[0.08    0.275    0.2    0.1],...
    'Tag','deselectinfobox',...
    'Enable','on',...
    'String','Deselect:',...
    'Style','text');

deselecteditbox=uicontrol('Parent',enterselection,...
    'Units','normalized',...
    'Position',[0.35    0.23    0.6    0.185],...
    'Tag','deselecteditbox',...
    'Enable','on',...
    'Style','edit',...
    'BackgroundColor','w',...
    'TooltipString','enter EntityIDs to be deselected',...
    'Callback',@deselecteditboxcallback);

function selecteditboxcallback(a,b)

 try
    tempstring=get(findobj(gcf,'Tag','selecteditbox'),'String');
    selectnow=eval(tempstring);
    FIND_GUIdata=get(findobj('Tag','FIND_GUI'),'UserData');
    myguiprops=get(findobj('Name','browseEntitiesGUI'),'UserData');
    if ~all(ismember(selectnow,1:length(FIND_GUIdata.IDselected)));return;end
    FIND_GUIdata.IDselected(selectnow)=1;
    entitiesonthispage=intersect(myguiprops.pageentries,selectnow);
    for ii=1:length(entitiesonthispage)
        set(findobj(findobj('Name','browseEntitiesGUI'),'Tag',num2str(entitiesonthispage(ii))),'Value',1)
    end
    set(findobj('Tag','FIND_GUI'),'UserData',FIND_GUIdata);
catch
    disp('oops')
end

function deselecteditboxcallback(a,b)

 try
    tempstring=get(findobj(gcf,'Tag','deselecteditbox'),'String');
    selectnow=eval(tempstring);
    FIND_GUIdata=get(findobj('Tag','FIND_GUI'),'UserData');
    myguiprops=get(findobj('Name','browseEntitiesGUI'),'UserData');
    if ~all(ismember(selectnow,1:length(FIND_GUIdata.IDselected)));return;end
    FIND_GUIdata.IDselected(selectnow)=0;
    entitiesonthispage=intersect(myguiprops.pageentries,selectnow);
    for ii=1:length(entitiesonthispage)
        set(findobj(findobj('Name','browseEntitiesGUI'),'Tag',num2str(entitiesonthispage(ii))),'Value',0)
    end
    set(findobj('Tag','FIND_GUI'),'UserData',FIND_GUIdata);
catch
    disp('oops')
end
