function simulateGammaGUI(varargin)
% Simulate gamma point processes GUI
%
% %%%%%%%%%%Parameters %%%%%%%%%%%%%%%%%
% Tmin Tmax -> Time bins
% k         -> order of the gamma process, k=1 is a Poisson process
% N         -> N realizations (or independent processes)
% l         -> Rate of the processes
%
% Usefull to generate test data and Null-Hypothesis regarding experimental
% data.
%
% R.MEIER Jan 2007, meier@biologie.uni-freiburg.de
%
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

global nsFile;

% Check if the spike Det GUI is already open
if ishandle(findobj('tag', 'SimProcFig'))
    close(findobj('tag', 'SimProcFig'));
end;

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT
global MESSAGEBAR_LEFT_OFFSET
global MESSAGEBAR_RIGHT_OFFSET


% pvpmod(varargin);
%
%
% if ~exist('nsFile')
%     disp('no data variable FOUND - creating an EMPTY one!')
%
%     nsFile.NeuralEvent=[];
% else
%     global nsFile;
% end

% if ~isstruct(nsFile)
%     error('specified data variable is not a struct')
%     return
% end

% Start the Spike Detection GUI
SimProcFig=figure('Units','characters',...
    'Position',[20 20 70 20], ...
    'Tag','SimProcFig', ...
    'Name','Gamma Process Simulation GUI',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'resize','off');


% panels
centralpanel=uipanel('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
    70 (20-MESSAGEBAR_PANEL_HEIGHT)],...
    'Tag','centralpanel',...
    'BackgroundColor', [0.8 0.8 0.8]);

messageBarpanel=uipanel('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[0 0 ...
    70 MESSAGEBAR_PANEL_HEIGHT],...
    'Tag','messageBarpanel');

% messageBar
messageBarpanelpos=get(messageBarpanel,'Position');
messageBar=uicontrol('Parent',messageBarpanel,...
    'Units','characters',...
    'Position',[(messageBarpanelpos(1)+MESSAGEBAR_LEFT_OFFSET) ...
    (messageBarpanelpos(2)) ...
    (messageBarpanelpos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
    LABEL_HEIGHT],...
    'Tag','simulateGammaGUI_messageBarText',...
    'Enable','on',...
    'String','',...
    'HorizontalAlignment','left',...
    'Style','text');


%% tmin,tmax,l,k,n variables NEEDED

NmeanValueEdit=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[3    13    20    LABEL_HEIGHT],...
    'Style','edit',...
    'String','5',...
    'Tag','n_realizations',...
    'Enable','on');
% text label
tmp_texthandle=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[3    15    20    LABEL_HEIGHT],...
    'Style','text',...
    'String','N realizations',...
    'Tag','dumbtxt',...
    'Enable','on');


% Tmin Tmax
VectorAnalogDataEdit=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[27    13    20    LABEL_HEIGHT],...
    'Style','edit',...
    'String','[0 10000]',...
    'Tag','VectorTminTmax',...
    'Enable','on');

% text label
tmp_texthandle=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[27    15    20    LABEL_HEIGHT],...
    'Style','text',...
    'String','[Tmin Tmax]',...
    'Tag','dumbtxt',...
    'Enable','on');


% l- the rate
VectorAnalogDataEdit=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[3    7   20    LABEL_HEIGHT],...
    'Style','edit',...
    'String','50',...
    'Tag','l_rate',...
    'Enable','on');

% text label
tmp_texthandle=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[3    9    20    LABEL_HEIGHT],...
    'Style','text',...
    'String','l (rate)',...
    'Tag','dumbtxt',...
    'Enable','on');



% K - the shape parameter
VectorAnalogDataEdit=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[27    7    20    LABEL_HEIGHT],...
    'Style','edit',...
    'String','1',...
    'Tag','k_shapepara',...
    'Enable','on');

% text label
tmp_texthandle=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[27    9    20    LABEL_HEIGHT],...
    'Style','text',...
    'String','k (Dist. shape)',...
    'Tag','dumbtxt',...
    'Enable','on');


% RUN Spike Detection button --> START !
RunDetection=uicontrol('Parent',SimProcFig,...
    'Units','characters',...
    'Position',[55    10    10    BUTTON_HEIGHT],...
    'Style','PushButton',...
    'String','RUN',...
    'Tag','RunProcessGenerator',...
    'Enable','on',...
    'Callback',@generate_process);


  % field to set EntityIDs of new neural data
    
    % if you want to append data to already existing data use identical IDs
    % if no entityIDs are set they will be generated staring with ID 1
    
    uicontrol('Parent',SimProcFig,...
        'Units','characters',...
        'Position',[3 3.5 30 LABEL_HEIGHT],...
        'Style','text',...
        'String','set data EntityID (optional) : ',...
        'Tag','simulateGamma_GUI_textNewNeuralEntityID',...
        'Enable','on');
    
      uicontrol('Parent',SimProcFig,...
        'Units','characters',...
        'Position',[36 3.5 15  LABEL_HEIGHT],...
         'Style','edit',...
        'String',[],...
        'Tag','simulateGamma_GUI_newNeuralEntityID',...
        'Enable','on');
        
      % field to set EntityIDs of new event data
     uicontrol('Parent',SimProcFig,...
        'Units','characters',...
        'Position',[3 2 30 LABEL_HEIGHT],...
        'Style','text',...
        'String','set trigger EntityID (optional) : ',...
        'Tag','simulateGamma_GUI_textNewEventEntityID',...
        'Enable','on');
    
      uicontrol('Parent',SimProcFig,...
        'Units','characters',...
        'Position',[36 2 15  LABEL_HEIGHT],...
         'Style','edit',...
        'String',[],...
        'Tag','simulateGamma_GUI_newEventEntityID',...
        'Enable','on');
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function generate_process(a,b)
%
% gather the parameters of the GUI and generate the proc.
%

% if this is the first access to the nsFile, generate it in the base
% workspace - else it won't return values ....

if ~exist('nsFile','var')
    evalin('base','global nsFile');
end

global nsFile;
try

    % posting 'busy' message
    postMessage('Busy - please wait...');

    tmp=findobj('Tag','l_rate');
    user_string =get(tmp(1),'String'); % use first VALUE IF MULTIPLE FIGURES ARE OPEN
    l_rate=str2num((user_string));

    tmp=findobj('Tag','k_shapepara');
    user_string =get(tmp(1),'String'); % use first VALUE IF MULTIPLE FIGURES ARE OPEN
    k_shapepara=str2num((user_string));

    tmp=findobj('Tag','VectorTminTmax');
    user_string =get(tmp(1),'String'); % use first VALUE IF MULTIPLE FIGURES ARE OPEN
    vectTminTmax=eval((user_string));

    tmp=findobj('Tag','n_realizations');
    user_string =get(tmp(1),'String'); % use first VALUE IF MULTIPLE FIGURES ARE OPEN
    n_realizations=str2num((user_string));
    
    tmpFig=findobj('Tag','simulateGamma_GUI_newNeuralEntityID');
    tmp=get(tmpFig(1),'String');
    newNeuralEntityID=str2num(tmp);
    
    tmpFig2=findobj('Tag','simulateGamma_GUI_newEventEntityID');
    tmp2=get(tmpFig2(1),'String');
    newEventEntityID=str2num(tmp2);
  
    simulateGamma('tMin',vectTminTmax(1),'tMax',vectTminTmax(2),'rateVector',l_rate,...
        'shapeParameter',k_shapepara,'nRealizations',n_realizations,...
        'newNeuralEntityID',newNeuralEntityID,'newEventEntityID',newEventEntityID);


    postMessage('...done.');
catch
    handleError(lasterror);
end
